//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document(Guid fileId, string fileName, int employee, byte[] fileData)
        {
            DocumentID = fileId;
            DocumentName = fileName;
            DocumentSource = fileData;
            Employee = employee;

        }
        public Document()
        {

        }
        public System.Guid DocumentID { get; set; }
        public byte[] DocumentSource { get; set; }
        public int Employee { get; set; }
        public string DocumentName { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
