//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeling
    {
        public int ID { get; set; }
        public string CurrentDeviations { get; set; }
        public string Complaints { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Employee { get; set; }
        public Nullable<int> Evaluation { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
