//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Test { get; set; }
        public int Employee { get; set; }
        public string Result { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Test Test1 { get; set; }
    }
}
